name: Security Policy Engine Gate

on: [push]

jobs:
  validate-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # STEP 1: We test the insecure code to prove the gate catches vulnerabilities
      - name: Run Security Gate on Insecure Code
        run: python policy_engine.py insecure_policy.json
        continue-on-error: true # We let this fail without stopping the whole job just for the demo

      # STEP 2: We test the secure code to prove it allows safe deployments
      - name: Run Security Gate on Secure Code
        run: python policy_engine.py secure_policy.json
